import { Invoice, BillingDetails, Item, DocumentType } from '@prisma/client'

export const mockInvoices: Invoice[] = [
    {
        id: 1000,
        documentType: DocumentType.INVOICE,
        invoiceNumber: 'INV-1000',
        invoiceDate: new Date(),
        dueDate: new Date(),
        billingDetailsId: 1000,
        customerName: 'John Doe',
        customerAddress: '123 Main St, New York, NY 10030',
        customerContact: '+252618977249',
        subtotal: 100,
        totalAmount: 100,
        paymentTerms: 'Cash',
        termsAndConditions: 'No terms and conditions',
        notes: 'No notes',
        createdBy: 'Abdi Zamed Mohamed',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 1002,
        documentType: DocumentType.QUOTATION,
        invoiceNumber: 'INV-1000',
        invoiceDate: new Date(),
        dueDate: new Date(),
        billingDetailsId: 1000,
        customerName: 'John Doe',
        customerAddress: '123 Main St, New York, NY 10030',
        customerContact: '+252618977249',
        subtotal: 100,
        totalAmount: 100,
        paymentTerms: 'Cash',
        termsAndConditions: 'No terms and conditions',
        notes: 'No notes',
        createdBy: 'Abdi Zamed Mohamed',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 1003,
        documentType: DocumentType.QUOTATION,
        invoiceNumber: 'INV-1000',
        invoiceDate: new Date(),
        dueDate: new Date(),
        billingDetailsId: 1000,
        customerName: 'John Doe',
        customerAddress: '123 Main St, New York, NY 10030',
        customerContact: '+252618977249',
        subtotal: 100,
        totalAmount: 100,
        paymentTerms: 'Cash',
        termsAndConditions: 'No terms and conditions',
        notes: 'No notes',
        createdBy: 'Ahmed Mohamed',
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]

export const mockBillingDetails: BillingDetails[] = [
    {
        id: 1000,
        name: 'John Doe',
        address: '123 Main St, New York, NY 10030',
        contact: '+252618977249',
    },
    {
        id: 1001,
        name: 'John Appleseed',
        address: '123 Main St, New York, NY 10030',
        contact: '+252618977248',
    },
    {
        id: 1002,
        name: 'John Hulk',
        address: '123 Main St, New York, NY 10030',
        contact: '+252618977247',
    },
]

export const mockItems: Item[] = [
    {
        id: 1000,
        description: 'Item 1',
        quantity: 1,
        unitPrice: 100,
    },
    {
        id: 1001,
        description: 'Item 2',
        quantity: 1,
        unitPrice: 100,
    },
    {
        id: 1001,
        description: 'Item 3',
        quantity: 1,
        unitPrice: 100,
    },
]
