import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './components/Providers'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import { StoreProvider } from '@/contexts/store-provider'
import NavbarLayout from './components/navs/nav-layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <StoreProvider>
                        <NavbarLayout />
                        {children}
                    </StoreProvider>
                </Providers>
            </body>
        </html>
    )
}
